# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellName', models.CharField(default=222, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envLight', models.CharField(max_length=10, null=True)),
                ('movement', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memID', models.FloatField()),
                ('memPW', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moniteringTime', models.DateTimeField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commendCode', models.CharField(max_length=100)),
                ('transmitTime', models.DateTimeField(blank=True, default=0)),
                ('receiveTime', models.DateTimeField(blank=True, default=0)),
                ('contents', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_code', models.FloatField(default=222)),
                ('re_loc', models.CharField(default='', max_length=100, null=True)),
                ('re_posX', models.FloatField(default=37.616573)),
                ('re_posY', models.FloatField(default=127.145068)),
                ('EOR', models.IntegerField(default=0)),
                ('RouteTable', models.FloatField(default=222)),
            ],
        ),
        migrations.CreateModel(
            name='StreetLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.FloatField()),
                ('posY', models.FloatField()),
                ('code', models.FloatField()),
                ('flag', models.CharField(max_length=10)),
                ('luminous', models.IntegerField(default=0, null=True)),
                ('loc', models.CharField(max_length=100, null=True)),
                ('ltAuto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(default=222, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='streetLight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stlsite.StreetLight'),
        ),
    ]
