# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0002_remove_environment_streetlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cellName',
            field=models.CharField(default='f', max_length=10),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zoneName',
            field=models.CharField(max_length=10),
        ),
    ]
