# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0003_auto_20170215_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlight',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Zone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repeater',
            name='re_loc',
            field=models.CharField(default='f', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='code',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='flag',
            field=models.CharField(blank=True, default='f', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='loc',
            field=models.CharField(blank=True, default='f', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='posX',
            field=models.FloatField(default=37.616573),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='posY',
            field=models.FloatField(default=127.145068),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zoneName',
            field=models.CharField(default='f', max_length=40),
        ),
    ]
