# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0004_auto_20170215_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cellName',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='repeater',
            name='RouteTable',
            field=models.CharField(default='Seoul', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeater',
            name='re_loc',
            field=models.CharField(default='Seoul', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='flag',
            field=models.CharField(blank=True, default='default', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='loc',
            field=models.CharField(blank=True, default='default', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zoneName',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
