# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0005_auto_20170216_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeater',
            name='RouteTable',
            field=models.CharField(default='Route1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeater',
            name='re_code',
            field=models.IntegerField(default=222),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
