# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0006_auto_20170216_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeater',
            name='cell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Cell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streetlight',
            name='cell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Cell'),
            preserve_default=False,
        ),
    ]
