# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0007_auto_20170216_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='streetLight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.StreetLight'),
            preserve_default=False,
        ),
    ]
