# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0008_environment_streetlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeater',
            name='monitering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Monitering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streetlight',
            name='monitering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Monitering'),
            preserve_default=False,
        ),
    ]
