# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0009_auto_20170222_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeater',
            name='monitering',
        ),
        migrations.RemoveField(
            model_name='streetlight',
            name='monitering',
        ),
        migrations.AddField(
            model_name='monitering',
            name='cell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Cell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitering',
            name='repeater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Repeater'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitering',
            name='streetLight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.StreetLight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitering',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.Zone'),
            preserve_default=False,
        ),
    ]
