# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0012_auto_20170222_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitering',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='monitering',
            name='repeater',
        ),
        migrations.RemoveField(
            model_name='monitering',
            name='streetLight',
        ),
    ]
