# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0013_auto_20170222_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitering',
            name='zone',
        ),
        migrations.AddField(
            model_name='cell',
            name='CellMonitorTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repeater',
            name='repMonitorTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='streetlight',
            name='sTLMonitorTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='zoneMonitorTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Monitering',
        ),
    ]
