# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0015_auto_20170222_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zoneLat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='zoneLng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
