# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0016_auto_20170314_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField()),
                ('Lng', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stlsite.Zone')),
            ],
        ),
    ]
