# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0018_auto_20170314_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlight',
            name='ltAuto',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
