# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0019_auto_20170327_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='ZoneColor',
            field=models.CharField(default='#1E90FF', max_length=40),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='ltAuto',
            field=models.CharField(default='locked', max_length=10),
        ),
    ]
