# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0020_auto_20170329_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlight',
            name='IsRepeater',
            field=models.CharField(default='off', max_length=10),
        ),
    ]
