# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0022_auto_20170405_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeater',
            name='RouteTable',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='re_code',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='re_loc',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='re_posX',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='re_posY',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='repMonitorTime',
        ),
        migrations.AddField(
            model_name='repeater',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repeater',
            name='streetLight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stlsite.StreetLight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='ltAuto',
            field=models.CharField(default='UnLocked', max_length=10),
        ),
    ]
