# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0024_repeater_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repeater',
            old_name='destination',
            new_name='departure',
        ),
    ]
