# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0027_auto_20170418_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.CharField(max_length=10),
        ),
    ]
