# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0028_auto_20170418_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.SlugField(unique=True),
        ),
    ]
