# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0029_auto_20170418_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlight',
            name='switch',
            field=models.CharField(default='on', max_length=4),
        ),
    ]
