# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0030_streetlight_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField(default='192.168.10.21')),
                ('port', models.IntegerField(default='2000')),
            ],
        ),
    ]
