# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0031_ipport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commendNum',
            field=models.IntegerField(default='1'),
        ),
    ]
