# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0033_auto_20170531_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contents',
        ),
    ]
