# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlsite', '0035_auto_20170531_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiveTime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transmitTime',
        ),
        migrations.AlterField(
            model_name='order',
            name='commendNum',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
